site_name: Readme for Citrix Virtual Channel SDK 1809
site_description: Readme for Citrix Virtual Channel SDK 1809
theme_dir: citrix-sdk
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: true
  - toc:
     anchorlink: true

pages:
  - Overview: index.md
